---
- connection: local
  hosts: localhost
  sudo: true
  remote_user: douglas
  vars:
    project: proxy
    ip_address: "192.168.1.{% if environment_tier=='development' %}92{% elif environment_tier=='production' %}2{% endif %}"
  roles:
    - role: stevenharradine.static-ip
      static_ip_address: "{{ ip_address }}"
    - role: stevenharradine.hostname
    - role: stevenharradine.haproxy
      haproxy_stats_enabled: no
      domain: "{{ ip_address }}"
  tasks:
    - name: create static ip
      template:
        src: templates/etc/haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0600
    - name: enable pseudo-forge
      lineinfile:
        dest: /home/douglas/.bashrc
        state: present
        line: "alias reforge='cd /home/douglas/playbook-{{ project }}/ && git pull && sudo ansible-galaxy install -r dependencies.yml --force && ansible-playbook playbook.yml -i hosts/{{ environment_tier }}'"
        insertafter: EOF
